### ISSUE TITLE
Kotlin 1.8.10 / JB Compose compiler 1.4.2 broke Jest sample

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/mosaic#145]
And probably others.

```
$ gw -q installDist && ./samples/jest/build/install/jest/bin/jest
 FAIL  tests/login.kt
 ‣ Failure on line 36 in tests/login.kt
 ‣ Failure on line 38 in tests/login.kt

 PASS  tests/reset-password.kt
 PASS  tests/forgot-password.kt
 FAIL  tests/signup.kt
 ‣ Failure on line 40 in tests/signup.kt

 RUNS  tests/post.kt
Time:  10s

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.remove(ArrayList.java:504)
	at androidx.compose.runtime.AbstractApplier.remove(Applier.kt:223)
	at com.jakewharton.mosaic.MosaicNodeApplier.remove(nodes.kt:185)
	at androidx.compose.runtime.ComposerImpl$realizeMovement$1.invoke(Composer.kt:3769)
	at androidx.compose.runtime.ComposerImpl$realizeMovement$1.invoke(Composer.kt:3769)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:808)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:585)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:503)
	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
	at com.jakewharton.mosaic.MosaicKt$runMosaic$2$2.invokeSuspend(mosaic.kt:81)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:518)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:500)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.jakewharton.mosaic.BlockingKt.runMosaicBlocking(blocking.kt:6)
	at example.JestKt.main(jest.kt:33)
	at example.JestKt.main(jest.kt)
```

**Comment by JakeWharton** [comment]
Appears to only affect `Static` usage
